services:
  byond:
    image: registry.neureka.dev/byond/byond:latest
    container_name: byond
    env_file:
      - .env
    networks:
      - byond
    ports:
      - "${BYOND_PORT:-1337}:${BYOND_PORT:-1337}"
    volumes:
      - data:/app/data
    restart: unless-stopped

networks:
  byond:
    name: byond

volumes:
  data:
