name: backport-byond-major

on:
  workflow_dispatch:
    inputs:
      major:
        description: BYOND major version to backport.
        required: true
        type: string
      force_overwrite:
        description: Overwrite existing image tags.
        required: false
        default: false
        type: boolean

jobs:
  setup-backport-byond-major:
    name: "Setup Backport: BYOND Major"
    uses: forgejo/workflows/.forgejo/workflows/backport-byond-major.yaml@main
    with:
      major: ${{ inputs.major }}
      context: .
      file: Dockerfile
      platforms: linux/386
      existing-tag-behavior: ${{ inputs.force_overwrite && 'overwrite' || 'skip' }}
      push: true
    secrets:
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
